# Generated by Django 5.2.7 on 2026-03-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_roomtype_alter_register_id_alter_website_id_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_number',
            field=models.IntegerField(default=1),
        ),
    ]
