# Generated by Django 6.0.3 on 2026-03-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_booking_payment_mode_booking_phone_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='id_proof_photo',
            field=models.ImageField(blank=True, null=True, upload_to='id_proofs/'),
        ),
    ]
